version: "3"

volumes:
  db:

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/srv
      - ~/.aws:/root/.aws
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    environment: 
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on: 
      - postgres

  postgres:
    image: postgres:13.1-alpine
    container_name: local-test-postgres
    restart: unless-stopped
    ports: 
      - "5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  pgweb:
    container_name: local-test-pgweb
    restart: unless-stopped
    image: sosedoff/pgweb
    ports:
      - "22980:8081"
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/app?sslmode=disable
    depends_on:
      - postgres